name: Docker Publish - fiap-apptechchallenge

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout
    - name: ğŸ“¥ Checkout cÃ³digo
      uses: actions/checkout@v4

    # 2. (Opcional) Listar arquivos para debug
    - name: ğŸ“‚ Listar arquivos
      run: ls -R

    # 3. Login no Docker Hub
    - name: ğŸ” Login no Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 4. Build
    - name: ğŸ› ï¸ Build da imagem
      run: |
        docker build \
          -t rismair/fiap-apptechchallenge:latest \
          -f Fiap.CloudGames.Fase1.API/Dockerfile .   # â† ajuste se o Dockerfile estiver em outro lugar

    # 5. Push
    - name: ğŸš€ Push da imagem
      run: docker push rismair/fiap-apptechchallenge:latest
